name: blanco # project name
networks:
  main: # internal project's network name / total network name will be '{project_name} + "_" + {network_name}'
    driver: bridge
services:

  postgres: # service name
    image: postgres:16-bookworm
    container_name: blanco_postgres
    networks:
      - main
    expose: # network's internal port list
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: blanco

  cache:
    image: redis:7.4.2-bookworm
    container_name: blanco_redis
    networks:
      - main
    expose:
      - "6379"

  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: blanco_mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=admin
    networks:
      - main
    expose:
      - "27017"

  mongo-express:
    image: mongo-express:latest
    container_name: blanco_mongo-express
    ports: # external port mapping
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_SERVER=blanco_mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
    depends_on:
      - mongo
    networks:
      - main

  app:
    build:
      dockerfile: ./Dockerfile
    image: blanco_app
    container_name: blanco_app
    networks:
      - main
    ports:
      - "8080:8079"
    depends_on:
      - postgres
      - cache
      - mongo

  kafka_ui:
    image: provectuslabs/kafka-ui
    container_name: kafka_ui
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - main
    depends_on:
      - kafka

  kafka:
    image: bitnami/kafka
    container_name: kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - main

  transaction-interceptor:
    image: transaction-interceptor:latest
    container_name: transaction-interceptor
    ports:
      - "8082:8078"
    networks:
      - main
    depends_on:
      - kafka

