spring:
  application:
    name: Blanco

# postgres
  datasource:
    url: jdbc:postgresql://blanco_postgres:5432/blanco
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true # what is it?
      minimum-idle: 3
      maximum-pool-size: 10
      transaction-isolation: TRANSACTION_REPEATABLE_READ
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  data:
#    mongodb:
#      uri: mongodb://admin:secret@localhost:27017/admin


# logging
logging:
  level:
    root: INFO
    org.springframework: DEBUG
  file:
    name: logs/app.log
  pattern:
    #console: %d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n






